[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  headers = { Cache-Control = "no-cache" }

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
